### ISSUE TITLE
移植例程能够正常显示，但是在加入文件系统后，界面就无法显示

### ISSUE THREAD

**Issue by maohaixu** [zlgopen/awtk-stm32f103ze-raw#15]
我将awtk/demos/assets 放入sd卡中，路径是awtk/assets/default/raw/---

文件系统是调用的例程STM32H743 , 

现在在main中调用 assert(file_exist("0://awtk/assets/default/raw/fonts/default.ttf")); 通过调试可以知道文件是存在的，这样可以说明文件系统已经是对的了吗；然后 我在assets-mini.c中修改了一下
ret_t assets_init(void) {
  assets_manager_t* am = assets_manager();
#ifdef WITH_FS_RES
  assets_manager_preload(am, ASSET_TYPE_FONT, "default");
  assets_manager_preload(am, ASSET_TYPE_STYLE, "default");
#else
  assets_manager_add(am, font_default_18);
  assets_manager_add(am, image_bricks);
 ......
}
awtk_config.h 中 增加
#define WITH_FS_RES 1
#define APP_RES_ROOT "0://awtk/"
其他地方无改动，编译运行，界面显示白色，无其他显示。

**Comment by xianjimli** [comment]
103 不能定义WITH_FS_RES ，没有足够内存将资源从文件系统读入内存，资源只能放到flash中。

**Comment by maohaixu** [comment]
那大概需要多少内存才能将资源从文件系统中读取出来呢，我这边可以外挂一个sram；




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"jim"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月19日(星期五) 中午11:02
收件人:&nbsp;"zlgopen/awtk-stm32f103ze-raw"<awtk-stm32f103ze-raw@noreply.github.com&gt;;
抄送:&nbsp;"。"<1181107780@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zlgopen/awtk-stm32f103ze-raw] 移植例程能够正常显示，但是在加入文件系统后，界面就无法显示 (#15)





 
103 不能定义WITH_FS_RES ，没有足够内存将资源从文件系统读入内存，资源只能放到flash中。

**Comment by xianjimli** [comment]
这个要看具体情况，主要是图片和字体。外挂sram有多大

**Comment by maohaixu** [comment]
外挂了一个16m的sram；还有在哪里配置呢？实现呢


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: jim <notifications@github.com&gt;
发送时间: 2020年6月19日 17:44
收件人: zlgopen/awtk-stm32f103ze-raw <awtk-stm32f103ze-raw@noreply.github.com&gt;
抄送: maohaixu <1181107780@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[zlgopen/awtk-stm32f103ze-raw] 移植例程能够正常显示，但是在加入文件系统后，界面就无法显示 (#15)





 
这个要看具体情况，主要是图片和字体。外挂sram有多大

**Comment by xianjimli** [comment]
在platform_prepare中初始化内存：

https://github.com/zlgopen/awtk-stm32f103ze-raw/blob/master/awtk-port/platform.c

**Comment by maohaixu** [comment]
嗯，懂了。
