### ISSUE TITLE
使用awtk bin中的resgen.exe 将png文件转换成data数据后 无法显示。

### ISSUE THREAD

**Issue by maohaixu** [zlgopen/awtk-stm32f103ze-raw#16]
在使用awtk\demos\assets\default\中的图片和data数据 在平台中能够显示，但是我通过使用resgen工具将自己的图片转换后加入平台，却无法显示。

**Comment by xianjimli** [comment]
resgen生成的数据是没有解码的图像数据(如png)，103上一般没有足够的内存来解码，所以缺省是不能显示的。

如果有外接SRAM，而且在platform_prepare中指定了足够内存，可以在awtk_config.h中开启PNG解码。

**Comment by maohaixu** [comment]
是&nbsp;WITH_STB_IMAGE 这个宏定义吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "jim"<notifications@github.com&gt;; 
发送时间: 2020年6月22日(星期一) 中午11:33
收件人: "zlgopen/awtk-stm32f103ze-raw"<awtk-stm32f103ze-raw@noreply.github.com&gt;; 
抄送: "。"<1181107780@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [zlgopen/awtk-stm32f103ze-raw] 使用awtk bin中的resgen.exe 将png文件转换成data数据后 无法显示。 (#16)





 
resgen生成的数据是没有解码的图像数据(如png)，103上一般没有足够的内存来解码，所以缺省是不能显示的。
 
如果有外接SRAM，而且在platform_prepare中指定了足够内存，可以在awtk_config.h中开启PNG解码。

**Comment by xianjimli** [comment]
是的

**Comment by maohaixu** [comment]
我用这个路径下面的图片数据  如 awtk\demos\assets\default\inc\images\num_0.data 可以在显示屏中显示，这个data对应的图片为awtk\demos\assets\default\raw\images\x1\num_0.jpg吧；没有开启WITH_STB_IMAGE也是能显示的；那么这个图片是通过什么工具转换成data数据的呢?

**Comment by xianjimli** [comment]
imagegen

**Comment by maohaixu** [comment]
嗯 好的 我试试



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "jim"<notifications@github.com&gt;; 
发送时间: 2020年6月22日(星期一) 中午12:02
收件人: "zlgopen/awtk-stm32f103ze-raw"<awtk-stm32f103ze-raw@noreply.github.com&gt;; 
抄送: "。"<1181107780@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [zlgopen/awtk-stm32f103ze-raw] 使用awtk bin中的resgen.exe 将png文件转换成data数据后 无法显示。 (#16)





 
imagegen

**Comment by qianxufeng** [comment]
> resgen生成的数据是没有解码的图像数据(如png)，103上一般没有足够的内存来解码，所以缺省是不能显示的。
> 
> 如果有外接SRAM，而且在platform_prepare中指定了足够内存，可以在awtk_config.h中开启PNG解码。

這個内存最少需要多少少，在platform_prepare中

**Comment by xianjimli** [comment]
这个要看图片大小。
