### ISSUE TITLE
Development board purchase 

### ISSUE THREAD

**Issue by ajsb85** [zlgopen/awtk-stm32f103ze-raw#17]
Dear @xianjimli 

I cannot activate my account on Taobao.
Do you know another option for international shipping of this development board?
Thank you.

Thank you.

**Comment by ajsb85** [comment]
I found the board already.
But just to clarify.
The model is the Z3 right?

https://es.aliexpress.com/item/1005001794778646.html?spm=a2g0o.cart.0.0.40f63c00Vm8KzG&mp=1

**Comment by xianjimli** [comment]
I think it is. It may be necessary to modify a certain macro to select the correct LCD driver.

**Comment by xianjimli** [comment]
In addition, the STM32F103 has too little memory to run some basic functions. It is recommended to use the STMH7 development board, such as: [STM32H743](https://es.aliexpress.com/item/1005002762767566.html?spm=a2g0o.productlist.0.0.79bb5d50sIXJef&algo_pvid=7f5cd24c-b2b2-49f4-bb03-7948d395eac2&algo_expid=7f5cd24c-b2b2-49f4-bb03-7948d395eac2-0&btsid=0b01114516228634846884257eb6e1&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_)

**Comment by ajsb85** [comment]
Perfect!

Thank you very much.

**Comment by ajsb85** [comment]
BTW @xianjimli 

What do you think about this board: Ameba RTL8722DM (AMB 21)

![image](https://user-images.githubusercontent.com/663460/120878979-5bd4d680-c5c0-11eb-9d96-88262b577a67.png)

https://www.amebaiot.com/en/amebad/

**Comment by ajsb85** [comment]
Another question.
Do you have a plan to create a sample project for the STMH7?

**Comment by xianjimli** [comment]
Any development board is possible, but some porting work is required (usually not difficult). However, the development board that supports linux is the most convenient. linux provides framebuffer abstraction. Generally, AWTK can be run without modification.

**Comment by xianjimli** [comment]
This is STM32H7 porting demo: https://github.com/zlgopen/awtk-stm32h743iitx-freertos

**Comment by ajsb85** [comment]
Hi, @xianjimli 

Thank you for the answer.

Seems those board are more close to the porting demo setup

https://es.aliexpress.com/item/32922326035.html
https://es.aliexpress.com/item/32982856171.html

**Comment by xianjimli** [comment]
Yes, it is.

**Comment by ajsb85** [comment]
Seems this is the screen

https://es.aliexpress.com/item/32981167209.html

**Comment by xianjimli** [comment]
yes, I think so.

**Comment by ajsb85** [comment]
Ok, I bought the two items already.
It should arrive at the end of Jun.
Keep in touch.

**Comment by xianjimli** [comment]
Ok, good luck. 
Just ask me if you have any questions. 
Before the development board arrives, you can play AWTK on your PC.

**Comment by ajsb85** [comment]
![image](https://user-images.githubusercontent.com/663460/122046521-4ee58d80-cddf-11eb-9aa2-7e49fb16789f.png)
