### ISSUE TITLE
bitmap.c 编译报错

### ISSUE THREAD

**Issue by farewellbuaa** [zlgopen/awtk-stm32f103ze-raw#3]
..\awtk\src\base\bitmap.c(149): error:  #28: expression must have a constant value

rgba_t t = pixel_rgba8888_to_rgba((*p));

这个宏定义看起来没有什么问题，不知道为什么通不过编译。

**Comment by xianjimli** [comment]
编译器什么版本，我这里没问题。

**Comment by farewellbuaa** [comment]
我用的是keil 4版本的，你用哪个版本的啊，是ide自带的编译器还是gcc啊？

**Comment by xianjimli** [comment]
用keil 5吧，老版本的编译器可能有些问题。
