### ISSUE TITLE
keil5编译失败-没有darray文件和widget_pool文件

### ISSUE THREAD

**Issue by Fengguangda** [zlgopen/awtk-stm32f103ze-raw#4]
打开keil项目文件，导入对应的源文件，编译发现没有darray文件，请问darray文件是否变成了"awtk-master\awtk-master\src\tkc\array.c"，另外widget_pool文件实在没找到，编译的时候也没有使用这个文件，对项目运行不知道有没有影响

**Comment by xianjimli** [comment]
已修改，请取最新的代码试试。谢谢。
