### ISSUE TITLE
error:  #69: integer conversion resulted in truncation

### ISSUE THREAD

**Issue by guny** [zlgopen/awtk-stm32f103ze-raw#7]
将demo下载至本机，使用keil v4版本编译，发现以下异常：
Build target 'awtk'
compiling button.c...
..\awtk\src\widgets\button.c(213): error:  #69: integer conversion resulted in truncation
                            .on_event = button_on_event,
..\awtk\src\widgets\button.c: 0 warnings, 1 error
compiling button.c...
..\awtk\src\widgets\button.c(213): error:  #69: integer conversion resulted in truncation
                            .on_event = button_on_event,
..\awtk\src\widgets\button.c: 0 warnings, 1 error
compiling check_button.c...
..\awtk\src\widgets\check_button.c(151): error:  #69: integer conversion resulted in truncation
      .clone_properties = s_check_button_properties,
..\awtk\src\widgets\check_button.c(167): error:  #69: integer conversion resulted in truncation
      .clone_properties = s_check_button_properties,
..\awtk\src\widgets\check_button.c: 0 warnings, 2 errors
compiling dialog.c...
..\awtk\src\widgets\dialog.c(95): error:  #69: integer conversion resulted in truncation
                            .clone_properties = s_dialog_properties,
..\awtk\src\widgets\dialog.c: 0 warnings, 1 error
compiling window.c...
..\awtk\src\widgets\window.c(80): error:  #69: integer conversion resulted in truncation
                            .on_event = window_base_on_event,
..\awtk\src\widgets\window.c: 0 warnings, 1 error
compiling window_manager.c...
..\awtk\src\base\window_manager.c(852): error:  #69: integer conversion resulted in truncation
      .type = WIDGET_TYPE_WINDOW_MANAGER,
..\awtk\src\base\window_manager.c: 0 warnings, 1 error
compiling slider.c...
..\awtk\src\widgets\slider.c(456): error:  #69: integer conversion resulted in truncation
                            .clone_properties = s_slider_properties,
..\awtk\src\widgets\slider.c: 0 warnings, 1 error
compiling system_info.c...
..\awtk\src\base\system_info.c(216): error:  #69: integer conversion resulted in truncation
                                                       .get_prop = system_info_get_prop,
..\awtk\src\base\system_info.c: 0 warnings, 1 error
compiling pages.c...
..\awtk\src\widgets\pages.c(108): error:  #69: integer conversion resulted in truncation
                           .type = WIDGET_TYPE_PAGES,
..\awtk\src\widgets\pages.c(110): error:  #69: integer conversion resulted in truncation
                           .clone_properties = s_pages_clone_properties,
..\awtk\src\widgets\pages.c: 0 warnings, 2 errors
compiling edit.c...
..\awtk\src\widgets\edit.c(1119): error:  #69: integer conversion resulted in truncation
                          .clone_properties = s_edit_properties,
..\awtk\src\widgets\edit.c: 0 warnings, 1 error
compiling spin_box.c...
..\awtk\src\widgets\spin_box.c(34): error:  #69: integer conversion resulted in truncation
                              .clone_properties = s_edit_properties,
..\awtk\src\widgets\spin_box.c: 0 warnings, 1 error
compiling combo_box.c...
..\awtk\src\widgets\combo_box.c(150): error:  #69: integer conversion resulted in truncation
                               .type = WIDGET_TYPE_COMBO_BOX,
..\awtk\src\widgets\combo_box.c: 0 warnings, 1 error
compiling popup.c...
..\awtk\src\widgets\popup.c(116): error:  #69: integer conversion resulted in truncation
                           .clone_properties = s_popup_properties,
..\awtk\src\widgets\popup.c: 0 warnings, 1 error
compiling color_tile.c...
..\awtk\src\widgets\color_tile.c(82): error:  #69: integer conversion resulted in truncation
                                .set_prop = color_tile_set_prop,
..\awtk\src\widgets\color_tile.c: 0 warnings, 1 error
compiling system_bar.c...
..\awtk\src\widgets\system_bar.c(101): error:  #69: integer conversion resulted in truncation
                                .clone_properties = s_system_bar_properties,
..\awtk\src\widgets\system_bar.c: 0 warnings, 1 error
compiling overlay.c...
..\awtk\src\widgets\overlay.c(37): error:  #69: integer conversion resulted in truncation
                             .on_event = window_base_on_event,
..\awtk\src\widgets\overlay.c: 0 warnings, 1 error
"..\obj\awtk_demo1.axf" - 18 Error(s), 0 Warning(s).
Target not created

**Comment by xianjimli** [comment]
用Keil V5吧。
